version: '3.8'

services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    privileged: true
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/robots.txt:/var/www/html/robots.txt
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html

  certbot:
    container_name: certbot
    restart: always
    image: certbot/certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    ports:
      - "6000:80"
    depends_on:
      - nginx
    command: renew


volumes:
  www-html:
  etc-letsencrypt:
