version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/robots.txt:/var/www/html/robots.txt
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - nginx-cache:/var/cache/nginx
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    ports:
      - "6000:80"
    depends_on:
      - nginx
    command: renew


volumes:
  www-html:
  etc-letsencrypt:
  nginx-cache:
