version: '3.8'

services:
  nginx:
    image: nginx
    restart: always
    privileged: true
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/robots.txt:/var/www/html/robots.txt
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot -w /var/www/html --email mmlomonosov@gmail.com -d cloudgram.online -d *.cloudgram.online --cert-name=certfolder --key-type rsa --agree-tos --non-interactive
    ports:
      - "6000:80"


volumes:
  www-html:
  etc-letsencrypt:
